services:
  fichesenat:
    build: .
    container_name: fichesenat
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=10097
      - SITE_BRAND=senat
      - VAR_DIR=/app/var
    volumes:
      - ./var:/app/var
